name: main
on: [push, pull_request]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: coursier/cache-action@v5
        with:
          extraFiles: ".github/scripts/*.sh"
      - run: sbt scalafmtSbtCheck test
